openapi: 3.0.0
info:
  title: Transaction Microservice API
  version: 1.0.0
  description: API para la gestión de transacciones bancarias.
servers:
  - url: http://localhost:8082
    description: Local server
paths:
  /transacciones/deposito:
    post:
      summary: Registrar un depósito
      operationId: registrarDeposito
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '201':
          description: Depósito registrado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
  /transacciones/retiro:
    post:
      summary: Registrar un retiro
      operationId: registrarRetiro
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '201':
          description: Retiro registrado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
  /transacciones/transferencia:
    post:
      summary: Registrar una transferencia
      operationId: registrarTransferencia
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '201':
          description: Transferencia registrada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
  /transacciones/cuenta/{cuentaOrigenId}:
    get:
      summary: Obtener historial de transacciones por cuenta
      operationId: obtenerHistorialPorCuenta
      parameters:
        - name: cuentaOrigenId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Historial de transacciones obtenido exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
  /transacciones/historial:
    get:
      summary: Obtener historial completo de transacciones
      operationId: obtenerHistorialCompleto
      responses:
        '200':
          description: Historial completo obtenido exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
components:
  schemas:
    Transaction:
      type: object
      properties:
        id:
          type: string
        tipo:
          type: string
          enum:
            - DEPOSITO
            - RETIRO
            - TRANSFERENCIA
        monto:
          type: number
          format: double
        fecha:
          type: string
          format: date-time
        cuentaOrigenId:
          type: string
        cuentaDestinoId:
          type: string
      required:
        - tipo
        - monto
        - cuentaOrigenId